### ISSUE TITLE
cost_proxy error on Handwriting synthesis generate

### ISSUE THREAD

**Issue by lukemunn** [thaines/helit#4]
Hey there,

This looks like a really interesting project. I've managed to get it compiled on Mac OSX, the line graph viewer works well, the HST main functions perfectly, but when I hit generate, I get the following error:

Starting generation...
L1::Selecting Glyphs...
Traceback (most recent call last):
  File "/Users/lukeandkimberlee/helit/handwriting/hst/hst.py", line 613, in __generate
    glyph_list = select_glyphs_dp(txt[i], self.glyph_db, fetch_count, match_strength, wrong_place_cost, space_mult, cfunc, True)
  File "/Users/lukeandkimberlee/helit/handwriting/hst/generate.py", line 133, in select_glyphs_dp
    cost[j,i] = mult * cost_func(left, right)
  File "/Users/lukeandkimberlee/helit/handwriting/hst/costs.py", line 93, in end_dist_cost_rf
    cost_proxy = frf.load_forest('cost_proxy.rf')
  File "/Users/lukeandkimberlee/helit/handwriting/hst/frf/frf.py", line 43, in load_forest
    f = bz2.BZ2File(fn, 'r')
IOError: [Errno 2] No such file or directory: 'cost_proxy.rf'

There is no cost_proxy.rf in the 'hst' directory. Do I have to run one of the python files to generate it first, or am I missing something here?

BTW I'm using the twin_older fineliner line graph to test with if that matters.

**Comment by lukemunn** [comment]
Ah hadn't downloaded the Random Forest models from the homepage. A couple lines in the Github readme would be helpful I think, just so others can know which files to download and where to unzip them to.

**Comment by LittleHalfling** [comment]
@lukemunn  Hi, I'm having the same issues that you've talked about here. I cannot generate more than 1 letter at a time or else the same error occurs. Where did you unzip the random forest files to? I tried extracting them in hst to no avail.
